### ISSUE TITLE
Determine and add license

### ISSUE THREAD

**Issue by tjcouch-sil** [paranext/paranext#12]
As an architect, I need to know the license we are putting on our new code in order to start working on open source repositories.

We need to set the license file on each repository appropriately.

**Comment by tjcouch-sil** [comment]
@GlennPruitt did we agree to use MIT as the license for our repos? Or shall we revisit this topic?

**Comment by darren8c** [comment]
Mike C is going to work with the Assure Alliance with determining the correct licensing.  Right now it is SIL International and MIT
