### ISSUE TITLE
Get an approved name for Paranext

### ISSUE THREAD

**Issue by darren8c** [paranext/paranext#13]
The team would really like a long term name for this product.  It seems like their is an organizational level decision on whether this will keep the name Paratext or assume a new name.  

- If we would use a new name we could open up polls to organizations on coming up with a name.  
- If we keep the name Paratext, we need some sort of way to distinguish this application from Paratext 9.

**Comment by darren8c** [comment]
We were able to discuss this in Dallas with about 6 people with some creative ideas.  We were thinking about 2 different pulls that affect the naming of Paranext.  The first is the pull to show that we are building something new and open that the BT community would understand is open source and a platform for the community.  The second challenge is that we don't want to alienate the brand and lose momentum of long term adoption of users by leaving the Paratext name behind.  There was some forward movement behind using Paranext for the near future (2-n years).  

Two ideas for the longterm would be to rename it in the future possibly to NEXT, and keep a subtitle that points to Paratext.  The second idea is that we would rename to Paratext X or Paratext 10 when we deemed it was complete enough for users (not all users but a number we feel comfortable with).  

The longterm branding is unknown, but has some solid ideas.  In the meantime we thought that Paranext with some milestone branding would be the best for the next couple of years.  Paratext tech demo could be Paratext Genesis.  The next milestone could be something like Paratext Exo or Paratex Exodus.  That way we can clearly distinguish that when people have tried Paratext, but we are on a new milestone they can cleary know that this is a new version.  This can also help us communicate to other people in the Biblcal Tools Community what milestone they might want to come in and build extensions on, etc.

**Comment by GlennPruitt** [comment]
This year we will be working on "Paranext Genesis".  The focus of Genesis will be on a technical demonstration.  Working in collaboration with the BT community will be of the utmost importance.

**Comment by GlennPruitt** [comment]
- [ ] Present at the PAC on Feb 8, 2023:

- The development naming scheme "Paranext <milestone>"  will be presented as fact.  The first milestone is Genesis - the technical demo for 2023.  Tentatively, the next milestone will be Exodus, the MVP.
- The ultimate goal of Paranext is to eventually become "Paratext X".   This will be presented as our current intention, once the Paranext project reaches a sufficient level of maturity.  Once Paratext X is produced we will move Paratext 9 fully into maintenance mode.
- The concept of "Next.Bible" being the platform, and Paratext X being the product (from a marketing standpoint) will not be presented to the PAC, it is noise at this point, but something to keep in consideration over the next several years.

**Comment by irahopkinson** [comment]
@GlennPruitt Today at our Scrum review we talked about the possibility of eventually calling it something like **Paratext Studio**. This gives the sense of it being a platform where you might add a whole lot of other things to it. This keeps it separate but also links it to Paratext (v9). Additionally it can have its own version numbering starting at v1 and not need to start at v10 (X). We are not set on this but thought I would mention it since we discussed it.

**Comment by GlennPruitt** [comment]
@irahopkinson  I love the name **Paratext Studio**.  I agree with everything you mentioned but I have one big hesitation.  Unfolding Word has two main products; **translationCore** and **translationStudio**.  The name Paratext Studio could appear to be a merger of our products (or a takeover of their product).  If the relationship between our orgs continues to improve greatly, and if we end up reusing a lot of translationStudio in Paranext, then that could be a very good name indeed.  However, until that time I'd like to see how things progress between our orgs.  BTW, I'm not totally sold on Paratext X, but we have some time before we get to that point.  On the other hand I am pretty much sold on Paranext Genesis.

**Comment by FoolRunning** [comment]
@GlennPruitt, @darren8c, I'm going to call this task finished.
