### ISSUE TITLE
Hello World for Electron

### ISSUE THREAD

**Issue by GlennPruitt** [paranext/paranext#2]
As an architect I need to have a working example of a cross platform build.

Develop an application UI shell (an empty application frame) that can be built and deployed to Windows, Linux and Mac.
All necessary code should be checked into this repository.
Include a build on demand system for all three platforms.  

- [x] Add electron-react-boilerplate
- [ ] check x-platform builds through GHA
_Move to a new card for a future sprint_
- [ ] Add .NET Core
- [ ] check x-platform builds through GHA

**Comment by irahopkinson** [comment]
For **Add electron-react-boilerplate** there is a PR #8 but it hasn't merge since we aren't sure yet where things go in terms of repo organisation.

**Comment by irahopkinson** [comment]
On top of PR #8 (branch `feature/electron-react`) there is a branch `feature/wsl` that adds help for setting up WSL2 on Windows so one machine can develop and test on Windows and Linux. No PR yet, see above comment about merging.

**Comment by irahopkinson** [comment]
[Electron Forge Maker](https://www.electronforge.io/config/makers) package types:  AppX, deb, DMG, FLatpak, Pkg, RPM, Snapcraft, Squirrel.Windows, WiX MSI, Zip.
[Electron Bulider distributable](https://www.electron.build/configuration/mac) package types:
- macOS: dmg, mas, mas-dev, pkg, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir
- Windows: nsis, nsis-web (Web installer), portable (portable app without installation), appx, msi, squirrel, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir
- Linux: AppImage, flatpak, snap, deb, rpm, freebsd, pacman, p5p, apk, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, dir

**Comment by irahopkinson** [comment]
PR #11 adds publishing artifacts to a GH Release. We don't yet have secrets available to add on GH for signing.

**Comment by irahopkinson** [comment]
Runs on Windows 11:

![Image](https://user-images.githubusercontent.com/5582153/214718219-f353a019-9783-4cfc-9539-982d7c7295eb.png)

**Comment by irahopkinson** [comment]
Runs on MacOS:

![Image](https://user-images.githubusercontent.com/5582153/214718390-bf37d05d-0ace-4ce7-a53b-d25ff0d0b9cd.png)


![Image](https://user-images.githubusercontent.com/5582153/214718486-83e48d0f-cd5e-4a55-851b-bb3540ce0eb9.png)


Thanks @darren8c for testign this.

**Comment by irahopkinson** [comment]
On Linux (Ubuntu v22+) you need `libfuse2` to run `.AppImage` applications.
`sudo apt install libfuse2`
There are also other dependencies needed to run:
`sudo apt install libnss3 libgtk-3-1 libgbm1`

**Comment by irahopkinson** [comment]
PR [#10](https://github.com/paranext/paranext-core/pull/10) fixes the publishable release for `.AppImage` files on Linux by including used dependencies.
